#!/bin/sh

ver=$(echo "${DOCKER_TAG}"|cut -d- -f2)
if [ "$ver" ]; then
    ver="-$ver"
fi

docker run --privileged --rm tonistiigi/binfmt --install all
docker buildx create --use default

: > tags.txt
for layer in base python3; do
    tag=$layer$ver
    echo "############################################################"
    echo "### building layer '$layer' with tag '$tag'"
    echo "### TAGVER=$ver"
    echo "### creating '$DOCKER_REPO:$tag' with '$layer/Dockerfile'"
    echo "############################################################"

    docker buildx build \
           --push \
           --build-arg "TAGVER=$ver" \
           --tag "$DOCKER_REPO":"$DOCKER_TAG" \
           --platform linux/amd64,linux/arm64/v8 "${layer:-.}"
    res=$?
    if [ $res -ne 0 ]; then
        echo "Building layer $layer returned $res" >&2
        exit $res
    fi
    echo "$tag" >> tags.txt
done
